version: '2'
services:
    getdata:
        restart: 'no'
        build: ./getdata
        container_name: getdata
        volumes:
            - ./data:/data
        command: /runner/data-obtain.sh
    datasette:
        build: ./datasette
        volumes:
            - ./data:/data
        command: datasette serve -h 0.0.0.0 -p 8001 --cors /data/pp-monthly-update.db
        ports:
            - 80:8001
